export const CHANGE_LANG_REQUEST = 'CHANGE_LANG_REQUEST';
export const CHANGE_LANG = 'CHANGE_LANG';

export const SET_MONEY_AMOUNT_REQUEST = 'SET_MONEY_AMOUNT_REQUEST';
export const SET_MONEY_AMOUNT = 'SET_MONEY_AMOUNT';

export const DEPOSIT_MONEY_REQUEST = 'DEPOSIT_MONEY_REQUEST';
export const DEPOSIT_MONEY = 'DEPOSIT_MONEY';

export const TRANSACTION_MSG_REQUEST = 'TRANSACTION_MSG_REQUEST';
export const TRANSACTION_MSG = 'TRANSACTION_MSG';